//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EaglesManagement_Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITmanagementEntities1 : DbContext
    {
        public ITmanagementEntities1()
            : base("name=ITmanagementEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<dtproperty> dtproperties { get; set; }
        public DbSet<RunningNumber> RunningNumbers { get; set; }
        public DbSet<tblAccessList> tblAccessLists { get; set; }
        public DbSet<tblAccessListDetail> tblAccessListDetails { get; set; }
        public DbSet<tblAccessMA> tblAccessMAs { get; set; }
        public DbSet<tblAccessSoftware> tblAccessSoftwares { get; set; }
        public DbSet<tblCheckBackUp> tblCheckBackUps { get; set; }
        public DbSet<tblCheckCCTV> tblCheckCCTVs { get; set; }
        public DbSet<tblCheckFireWall> tblCheckFireWalls { get; set; }
        public DbSet<tblCheckMeterial> tblCheckMeterials { get; set; }
        public DbSet<tblCheckRouter> tblCheckRouters { get; set; }
        public DbSet<tblCheckServer> tblCheckServers { get; set; }
        public DbSet<tblCheckSwitch> tblCheckSwitches { get; set; }
        public DbSet<tblDepartment> tblDepartments { get; set; }
        public DbSet<tblEmployee> tblEmployees { get; set; }
        public DbSet<tblEmployee_out> tblEmployee_out { get; set; }
        public DbSet<tblEmployee_outdtl> tblEmployee_outdtl { get; set; }
        public DbSet<tblGenAutoNo> tblGenAutoNoes { get; set; }
        public DbSet<tblInventoryItem> tblInventoryItems { get; set; }
        public DbSet<tblITServiceSparepart> tblITServiceSpareparts { get; set; }
        public DbSet<tblITServiceTicket> tblITServiceTickets { get; set; }
        public DbSet<tblITServiceTicketDetail> tblITServiceTicketDetails { get; set; }
        public DbSet<tblMasterCode> tblMasterCodes { get; set; }
        public DbSet<tblMenu> tblMenus { get; set; }
        public DbSet<tblOutSiteService> tblOutSiteServices { get; set; }
        public DbSet<tblOutSiteServiceDetail> tblOutSiteServiceDetails { get; set; }
        public DbSet<tblOutSourceService> tblOutSourceServices { get; set; }
        public DbSet<tblOutSourceServiceDetail> tblOutSourceServiceDetails { get; set; }
        public DbSet<tblPurchaseRequistionDtl> tblPurchaseRequistionDtls { get; set; }
        public DbSet<tblPurchaseRequistionHdr> tblPurchaseRequistionHdrs { get; set; }
        public DbSet<tblRecordProduct> tblRecordProducts { get; set; }
        public DbSet<tblRecordProductDtl> tblRecordProductDtls { get; set; }
        public DbSet<tblRentDevice> tblRentDevices { get; set; }
        public DbSet<tblRentDeviceDetail> tblRentDeviceDetails { get; set; }
        public DbSet<tblRepair> tblRepairs { get; set; }
        public DbSet<tblRepairDetail> tblRepairDetails { get; set; }
        public DbSet<tblUser> tblUsers { get; set; }
        public DbSet<tblUserMenu> tblUserMenus { get; set; }
        public DbSet<tblParty> tblParties { get; set; }
        public DbSet<tblPartyAddress> tblPartyAddresses { get; set; }
        public DbSet<tblUserGroup> tblUserGroups { get; set; }
    }
}
