//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EaglesManagement_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccessSoftware
    {
        public string AccessNo { get; set; }
        public string Software { get; set; }
        public Nullable<int> Issetup { get; set; }
        public string UserBy { get; set; }
        public Nullable<System.DateTime> UserDate { get; set; }
    }
}
