//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EaglesManagement_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccessMA
    {
        public string AccessNo { get; set; }
        public string MAyear { get; set; }
        public int Cycle { get; set; }
        public Nullable<int> ISMA { get; set; }
        public Nullable<System.DateTime> MAdate { get; set; }
        public string Observe { get; set; }
        public string Find { get; set; }
        public string Improve { get; set; }
        public string UserBy { get; set; }
        public Nullable<System.DateTime> UserDate { get; set; }
    }
}
