//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EaglesManagement_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCheckServer
    {
        public string ID { get; set; }
        public string DateSave { get; set; }
        public string ServerName { get; set; }
        public string IP { get; set; }
        public string Location { get; set; }
        public string InterfaceStatus { get; set; }
        public string ResponseTime { get; set; }
        public string Heat { get; set; }
        public string UtilizationCPU { get; set; }
        public string UtilizationMemory { get; set; }
        public string UtilizationDisk { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
