//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EaglesManagement_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCheckFireWall
    {
        public string ID { get; set; }
        public string DateSave { get; set; }
        public string Device { get; set; }
        public string IP { get; set; }
        public string Location { get; set; }
        public string WebBrowser { get; set; }
        public string StatusWAN { get; set; }
        public string StatusInternal { get; set; }
        public string UtilizationCPU { get; set; }
        public string UtilizationMemory { get; set; }
        public string StatusCon { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
