//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EaglesManagement_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCheckMeterial
    {
        public string ID { get; set; }
        public string DateSave { get; set; }
        public string AirName { get; set; }
        public string AirLocation { get; set; }
        public string TimeAir1 { get; set; }
        public string TimeAir2 { get; set; }
        public string TemServerName { get; set; }
        public string ServerLocation { get; set; }
        public string TemDs { get; set; }
        public string TemVM { get; set; }
        public string TemSAN { get; set; }
        public string ADSLName { get; set; }
        public string ADSLLocal { get; set; }
        public string StatusADSL { get; set; }
        public string Modem1Name { get; set; }
        public string Modem1Location { get; set; }
        public string Modem1Status1 { get; set; }
        public string Modem1Status2 { get; set; }
        public string Modem2Name { get; set; }
        public string Modem2Location { get; set; }
        public string Modem2Status1 { get; set; }
        public string Modem2Status2 { get; set; }
        public string GsmName { get; set; }
        public string GsmLocation { get; set; }
        public string GsmStatus1 { get; set; }
        public string GsmStatus2 { get; set; }
        public string GsmStatus3 { get; set; }
        public string GsmStatus4 { get; set; }
        public string KVMName { get; set; }
        public string KVMLocation { get; set; }
        public string KVMStatus1 { get; set; }
        public string KVMStatus2 { get; set; }
        public string KVMStatus3 { get; set; }
        public string KVMStatus4 { get; set; }
        public string KVMStatus5 { get; set; }
        public string KVMStatus6 { get; set; }
        public string KVMStatus7 { get; set; }
        public string KVMStatus8 { get; set; }
        public string HDDName { get; set; }
        public string HDDLocation { get; set; }
        public string HDDStatus1 { get; set; }
        public string HDDStatus2 { get; set; }
        public string HDDStatus3 { get; set; }
        public string HDDStatus4 { get; set; }
        public string HDDStatus5 { get; set; }
        public string HDDStatus6 { get; set; }
        public string MobileName { get; set; }
        public string MobileIP { get; set; }
        public string MobileLocation { get; set; }
        public string MobileReboot { get; set; }
        public string MobileConStatus { get; set; }
        public string HWName { get; set; }
        public string HWIP { get; set; }
        public string HWLocation { get; set; }
        public string HWStatus1 { get; set; }
        public string NoteHW1 { get; set; }
        public string HWStatus2 { get; set; }
        public string NoteHW2 { get; set; }
        public string HWStatus3 { get; set; }
        public string NoteHW3 { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
