//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EaglesManagement_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDepartment
    {
        public string Branch { get; set; }
        public string Party { get; set; }
        public string Department { get; set; }
        public string Manager { get; set; }
        public string A_Manager { get; set; }
        public Nullable<int> Status { get; set; }
        public string Userby { get; set; }
        public Nullable<System.DateTime> Lastupdate { get; set; }
    }
}
