//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EaglesManagement_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee_outdtl
    {
        public int id { get; set; }
        public Nullable<int> emp_card { get; set; }
        public Nullable<int> other_card { get; set; }
        public Nullable<System.DateTime> date_exp { get; set; }
        public Nullable<int> tel { get; set; }
        public Nullable<int> notebook_data { get; set; }
    }
}
