//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EaglesManagement_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGenAutoNo
    {
        public string TypeCode { get; set; }
        public string RunNo { get; set; }
        public string MountNo { get; set; }
        public string YearNo { get; set; }
        public string DigitNo { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
