//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EaglesManagement_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInventoryItem
    {
        public string Itemcode { get; set; }
        public string Itemname { get; set; }
        public string TypeUse { get; set; }
        public string TypeEquipment { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Vendor { get; set; }
        public string Userby { get; set; }
        public Nullable<System.DateTime> Lastupdate { get; set; }
    }
}
