//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EaglesManagement_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblITServiceSparepart
    {
        public string TicketNo { get; set; }
        public decimal RowID { get; set; }
        public Nullable<System.DateTime> RequestOrderDate { get; set; }
        public string RequestOrderBy { get; set; }
        public string ApprovedBy { get; set; }
        public string RequestOrderDetail { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> SumTotal { get; set; }
        public string SupplierName { get; set; }
        public string QTYVaranty { get; set; }
        public string UnitVaranty { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
