//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EaglesManagement_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblITServiceTicket
    {
        public string TicketNo { get; set; }
        public Nullable<System.DateTime> TickDate { get; set; }
        public string BranchRequest { get; set; }
        public string RequestFrom { get; set; }
        public string RequestBy { get; set; }
        public string IPAddress { get; set; }
        public string RemoteType { get; set; }
        public string AssigeJobTo { get; set; }
        public Nullable<System.DateTime> CloseJOBDate { get; set; }
        public string JOBStatus { get; set; }
        public string ComputerName { get; set; }
        public string JobUserName { get; set; }
        public string JobPassword { get; set; }
        public string RequestDetail { get; set; }
        public Nullable<decimal> TotalCostService { get; set; }
        public string BackRepairComplete { get; set; }
        public string Evaluation1 { get; set; }
        public string Evaluation2 { get; set; }
        public string Evaluation3 { get; set; }
        public string Evaluation4 { get; set; }
        public string Evaluation5 { get; set; }
        public string Evaluation6 { get; set; }
        public string EvaluationBy { get; set; }
        public Nullable<System.DateTime> EvaluationDate { get; set; }
        public string EvaluationRemark { get; set; }
        public string StatusEvaluation { get; set; }
        public string TicketType { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<System.DateTime> EstimateDate { get; set; }
        public Nullable<int> DateDiffEstimate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<int> DateDiff { get; set; }
        public string DepartmentRequest { get; set; }
        public string RepairNo { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
