//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EaglesManagement_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOutSourceService
    {
        public string TicketNo { get; set; }
        public string ServiceNo { get; set; }
        public Nullable<System.DateTime> ServiceDate { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierName { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string ReceivedBy { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
        public Nullable<System.DateTime> EstimateDate { get; set; }
        public Nullable<System.DateTime> ActualDate { get; set; }
        public Nullable<int> QtyOfWaranty { get; set; }
        public string UnitWaranty { get; set; }
        public Nullable<System.DateTime> StartWaranty { get; set; }
        public Nullable<System.DateTime> EndWaranty { get; set; }
        public Nullable<double> EstimatePrice { get; set; }
        public Nullable<double> ActualPrice { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
