//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EaglesManagement_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchaseRequistionDtl
    {
        public string PRPHNO { get; set; }
        public string Itemcode { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string QtyUnit { get; set; }
        public string Userby { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string Detail { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
