//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EaglesManagement_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblParty
    {
        public string PartyCode { get; set; }
        public string PartyFullName { get; set; }
        public string PartyLocalCode { get; set; }
        public string PartyLocalName { get; set; }
        public string PartyLocation { get; set; }
        public string PartyCountry { get; set; }
        public string RegistrationNo { get; set; }
        public string PartyTypeCode { get; set; }
        public string PartyTypeName { get; set; }
        public string CommissionToSales { get; set; }
        public string IATACode { get; set; }
        public string Remarks { get; set; }
        public string PartyStatus { get; set; }
        public string MessageHubID { get; set; }
        public string OtherSystemPartyID { get; set; }
        public string FormID { get; set; }
        public string Shipper { get; set; }
        public string Consignee { get; set; }
        public string Branch_Agent { get; set; }
        public string Co_Loader { get; set; }
        public string Trucking { get; set; }
        public string ShippingLine { get; set; }
        public string Vendor { get; set; }
        public string ContainerYard { get; set; }
        public string Warehouse { get; set; }
        public string Bank { get; set; }
        public string Factory { get; set; }
        public string Customer { get; set; }
        public string Broker { get; set; }
        public string AirLine { get; set; }
        public string EndCustomer { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
