//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EaglesManagement_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchaseRequistionHdr
    {
        public string PRPHNo { get; set; }
        public Nullable<int> IsPR { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public Nullable<System.DateTime> DateBuy { get; set; }
        public Nullable<System.DateTime> DateRequire { get; set; }
        public string Department { get; set; }
        public string Party { get; set; }
        public string Branch { get; set; }
        public string UserApp1 { get; set; }
        public string UserApp2 { get; set; }
        public Nullable<int> status { get; set; }
        public string Createby { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string Userby { get; set; }
        public Nullable<System.DateTime> Lastupdate { get; set; }
        public Nullable<int> StatusMail { get; set; }
        public string ApproveBy { get; set; }
        public Nullable<int> StatusCancel { get; set; }
        public string UserNameApp1 { get; set; }
        public string UserNameApp2 { get; set; }
        public string UserApp3 { get; set; }
    }
}
