//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EaglesManagement_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRecordProduct
    {
        public string SNNo { get; set; }
        public Nullable<int> Ishw { get; set; }
        public Nullable<int> IsStock { get; set; }
        public string ItemCodeNO { get; set; }
        public string Type { get; set; }
        public string Location { get; set; }
        public string Detail { get; set; }
        public Nullable<System.DateTime> StartGuarantee { get; set; }
        public Nullable<System.DateTime> EndGuarantee { get; set; }
        public string Remark { get; set; }
        public string CreatBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
