//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EaglesManagement_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRecordProductDtl
    {
        public string SNno { get; set; }
        public int RepairNo { get; set; }
        public string ServiceName { get; set; }
        public Nullable<System.DateTime> RepairDate { get; set; }
        public Nullable<int> StatusRepair { get; set; }
    }
}
