//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EaglesManagement_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRepairDetail
    {
        public string RepairNo { get; set; }
        public Nullable<System.DateTime> DateCompany { get; set; }
        public Nullable<System.DateTime> DateRepair { get; set; }
        public string TimeRepair { get; set; }
        public string CompanyRepair { get; set; }
        public string CompanyPhone { get; set; }
        public string RepairMan { get; set; }
        public string RepairManPhone { get; set; }
        public Nullable<int> TypePrice { get; set; }
        public Nullable<int> Warranty { get; set; }
        public Nullable<decimal> PriceAll { get; set; }
        public string AppPrice { get; set; }
        public Nullable<System.DateTime> DateRepairMan { get; set; }
        public string TimeRepairMan { get; set; }
        public Nullable<int> Normal { get; set; }
        public string AbNormal { get; set; }
        public string Note { get; set; }
        public string ManCheck { get; set; }
        public Nullable<System.DateTime> DateCheck { get; set; }
        public string UserBy { get; set; }
        public Nullable<System.DateTime> UserDate { get; set; }
    }
}
