//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EaglesManagement_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRentDevice
    {
        public string RentNo { get; set; }
        public Nullable<System.DateTime> RentDate { get; set; }
        public string RentOwner { get; set; }
        public string DeptOwner { get; set; }
        public string IssuedBy { get; set; }
        public Nullable<System.DateTime> IssuedDate { get; set; }
        public string ReceivedBy { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string ObjectiveofRent { get; set; }
        public string PlaceOfUsed { get; set; }
        public string StatusFinish { get; set; }
        public string Remarks { get; set; }
        public string StatusOfRent { get; set; }
        public string CreatBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
