//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EaglesManagement_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserMenu
    {
        public string UserName { get; set; }
        public string Program { get; set; }
        public Nullable<int> status { get; set; }
        public string UserBy { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    }
}
