//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EaglesManagement_Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblUser
    {
        public string UserName { get; set; }
        public string Name { get; set; }
        public string Dept { get; set; }
        public string Branch { get; set; }
        public string Party { get; set; }
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public string Mail { get; set; }
    }
}
